// This file is generated by Simplicity Studio.  Please do not edit manually.
//
//

// This file contains the mapping for the command line configuration

#include "app/framework/include/af.h"
#include "app/framework/cli/custom-cli.h"
#include EMBER_AF_API_COMMAND_INTERPRETER2

void emAfCliBsendCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const bsendCommandArguments[] = {
  "Source endpoint to send a binding based message from",
  NULL
};
#endif


void changeKeyCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const changekeyLinkCommandArguments[] = {
  "The link key provided as a 16 byte array",
  NULL
};
#endif


void changeKeyCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const changekeyNetworkCommandArguments[] = {
  "The network key provided as a 16 byte array",
  NULL
};
#endif


static EmberCommandEntry emberCommandChangekeyTable[] = {
  emberCommandEntryActionWithDetails("link", changeKeyCommand, "b", "Change the link key to the one provided in the 16 byte array argument  ...", changekeyLinkCommandArguments),
  emberCommandEntryActionWithDetails("network", changeKeyCommand, "b", "Change the network key to the 16 byte array provided as an argument to ...", changekeyNetworkCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPrintAllOff(void);
void emberAfPrintAllOn(void);
void printOffCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const debugprintOffCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};
#endif


void printOnCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const debugprintOnCommandArguments[] = {
  "The debug area mask listed in the <application>.h file",
  NULL
};
#endif


void emberAfPrintStatus(void);
static EmberCommandEntry emberCommandDebugprintTable[] = {
  emberCommandEntryActionWithDetails("all_off", emberAfPrintAllOff, "", "Turns off all debug printing", NULL),
  emberCommandEntryActionWithDetails("all_on", emberAfPrintAllOn, "", "Turns on all compiled in debug printing", NULL),
  emberCommandEntryActionWithDetails("off", printOffCommand, "u", "Turns off compiled in debug printing for a specific debug printing are ...", debugprintOffCommandArguments),
  emberCommandEntryActionWithDetails("on", printOnCommand, "u", "Turns on compiled in debug printing for a specific debug printing area ...", debugprintOnCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPrintStatus, "", "Prints out the current settings for debug printing on the device", NULL),
  emberCommandEntryTerminator(),
};
void echoCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const echoCommandArguments[] = {
  "bool indicating whether to turn echo on (1) or off (0)",
  NULL
};
#endif


void enableDisableEndpoint(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const endpointDisableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};
#endif


void enableDisableEndpoint(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const endpointEnableCommandArguments[] = {
  "Endpoint in question.",
  NULL
};
#endif


void endpointPrint(void);
static EmberCommandEntry emberCommandEndpointTable[] = {
  emberCommandEntryActionWithDetails("disable", enableDisableEndpoint, "u", "Disable the endpoint for processing ZCL messages.", endpointDisableCommandArguments),
  emberCommandEntryActionWithDetails("enable", enableDisableEndpoint, "u", "Enable the endpoint for processing ZCL messages.", endpointEnableCommandArguments),
  emberCommandEntryActionWithDetails("print", endpointPrint, "", "Print the status of all the endpoints.", NULL),
  emberCommandEntryTerminator(),
};
void printEvents(void);
void helpCommand(void);
void emAfCliInfoCommand(void);
void interpanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const interpanGroupCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};
#endif


void interpanLongCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const interpanLongCommandArguments[] = {
  "long ieee address to send the interpan message to",
  "two byte destination PA ID",
  "two byte destination profile ID",
  "two byte options",
  NULL
};
#endif


void interpanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const interpanShortCommandArguments[] = {
  "group id to send to",
  "destination pan id",
  "destination profile ID",
  NULL
};
#endif


static EmberCommandEntry emberCommandInterpanTable[] = {
  emberCommandEntryActionWithDetails("group", interpanCommand, "vvv", "send an interpan message to a group id.", interpanGroupCommandArguments),
  emberCommandEntryActionWithDetails("long", interpanLongCommand, "bvvv", "Send an interpan message to a long address (8 byte eui64)", interpanLongCommandArguments),
  emberCommandEntryActionWithDetails("short", interpanCommand, "vvv", "Send an interpan message to a short id.", interpanShortCommandArguments),
  emberCommandEntryTerminator(),
};
void keysClearCommand(void);
void keysDeleteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const keysDeleteCommandArguments[] = {
  "index into the security key table",
  NULL
};
#endif


void keysPrintCommand(void);
static EmberCommandEntry emberCommandKeysTable[] = {
  emberCommandEntryActionWithDetails("clear", keysClearCommand, "", "Clear all security keys", NULL),
  emberCommandEntryActionWithDetails("delete", keysDeleteCommand, "u", "Delete a security key from a given index", keysDeleteCommandArguments),
  emberCommandEntryActionWithDetails("print", keysPrintCommand, "", "Print all security keys out to the command line.", NULL),
  emberCommandEntryTerminator(),
};
void printAllLibraryStatus(void);
void networkPermitJoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkBroadPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};
#endif


void networkChangeChannelCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkChangeChannelCommandArguments[] = {
  "The channel to change to.",
  NULL
};
#endif


void changeKeepAliveModeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkChangeKeepAliveModeCommandArguments[] = {
  "The keep alive mode.",
  NULL
};
#endif


void networkExtendedPanIdCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkExtpanidCommandArguments[] = {
  "The bytes for the extended pan id",
  NULL
};
#endif


void findJoinableNetworkCommand(void);
void findUnusedPanIdCommand(void);
static EmberCommandEntry emberCommandNetworkFindTable[] = {
  emberCommandEntryActionWithDetails("joinable", findJoinableNetworkCommand, "", "Begin a search for a joinable networ ...", NULL),
  emberCommandEntryActionWithDetails("unused", findUnusedPanIdCommand, "", "Begin a search for an unused Channel and Pan I ...", NULL),
  emberCommandEntryTerminator(),
};
void networkFormCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkFormCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};
#endif


void networkIdCommand(void);
void networkInitCommand(void);
void networkCheckPjoinCommand(void);
void networkJoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkJoinCommandArguments[] = {
  "The channel on which to form the network",
  "One byte signed value indicating the TX power that the radio should be ...",
  "Two byte pan id for the network",
  NULL
};
#endif


void networkLeaveCommand(void);
void networkMultiPhyStartCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkMultiPhyStartCommandArguments[] = {
  "The page on which to form the network.",
  "The channel on which to form the network.",
  "One byte signed value indicating the TX power that the radio should be ...",
  "",
  NULL
};
#endif


void networkMultiPhyStopCommand(void);
void networkPermitJoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkPjoinCommandArguments[] = {
  "Number of seconds during which devices will be allowed to join the net ...",
  NULL
};
#endif


void networkRejoinCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkRejoinCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  NULL
};
#endif


void networkRejoinDiffDeviceTypeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkRejoinDiffDeviceTypeCommandArguments[] = {
  "Boolean indicating whether the device can rejoin secure or no ...",
  "4 byte channel mask which should be used to search for the network to  ...",
  "An enumeration indicating the device type to rejoin a ...",
  NULL
};
#endif


void networkSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkSetCommandArguments[] = {
  "The network index to use for CLI commands",
  NULL
};
#endif


void networkChangeChildTimeoutOptionMaskCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const networkTimeoutOptionMaskCommandArguments[] = {
  "The timeout option mask.",
  NULL
};
#endif


static EmberCommandEntry emberCommandNetworkTable[] = {
  emberCommandEntryActionWithDetails("broad-pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds AND broadc ...", networkBroadPjoinCommandArguments),
  emberCommandEntryActionWithDetails("change-channel", networkChangeChannelCommand, "u", "Attempts to change device over to a different channel given in the cha ...", networkChangeChannelCommandArguments),
  emberCommandEntryActionWithDetails("change-keep-alive-mode", changeKeepAliveModeCommand, "u", "Switch between different keep alive modes supported by a router", networkChangeKeepAliveModeCommandArguments),
  emberCommandEntryActionWithDetails("extpanid", networkExtendedPanIdCommand, "b", "Write the extended pan id for the device.", networkExtpanidCommandArguments),
  emberCommandEntrySubMenu("find", emberCommandNetworkFindTable, ""),
  emberCommandEntryActionWithDetails("form", networkFormCommand, "usv", "Create a network on the given channel, power and panId.", networkFormCommandArguments),
  emberCommandEntryActionWithDetails("id", networkIdCommand, "", "Prints the current Node ID, EUI64, and Pan ID.", NULL),
  emberCommandEntryActionWithDetails("init", networkInitCommand, "", "Initialize a network; this is a test command used for tc-swap-out test ...", NULL),
  emberCommandEntryActionWithDetails("isopen", networkCheckPjoinCommand, "", "Check if and for how long the network is open.", NULL),
  emberCommandEntryActionWithDetails("join", networkJoinCommand, "usv", "Join an existing network on the given channel, power and panId.", networkJoinCommandArguments),
  emberCommandEntryActionWithDetails("leave", networkLeaveCommand, "", "Leave the current network.", NULL),
  emberCommandEntryActionWithDetails("multi-phy-start", networkMultiPhyStartCommand, "uus*", "To start multi phy interface other than native and form the networ ...", networkMultiPhyStartCommandArguments),
  emberCommandEntryActionWithDetails("multi-phy-stop", networkMultiPhyStopCommand, "", "Terminates the multi phy interface", NULL),
  emberCommandEntryActionWithDetails("pjoin", networkPermitJoinCommand, "u", "Permit joining on the network for a given number of seconds", networkPjoinCommandArguments),
  emberCommandEntryActionWithDetails("rejoin", networkRejoinCommand, "uw", "Rejoin an existing network in a secure or insecure manner.", networkRejoinCommandArguments),
  emberCommandEntryActionWithDetails("rejoin-diff-device-type", networkRejoinDiffDeviceTypeCommand, "uwu", "Rejoin an existing network in a secure or insecure manner with a diffe ...", networkRejoinDiffDeviceTypeCommandArguments),
  emberCommandEntryActionWithDetails("set", networkSetCommand, "u", "Set the network index used by all future CLI command ...", networkSetCommandArguments),
  emberCommandEntryActionWithDetails("timeout-option-mask", networkChangeChildTimeoutOptionMaskCommand, "v", "Attempts to change child timeout option mask to filter out undesirable ...", networkTimeoutOptionMaskCommandArguments),
  emberCommandEntryTerminator(),
};
void optionApsRetryCommand(void);
void optionApsRetryCommand(void);
void optionApsRetryCommand(void);
static EmberCommandEntry emberCommandOptionApsretryTable[] = {
  emberCommandEntryActionWithDetails("default", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("off", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryActionWithDetails("on", optionApsRetryCommand, "", "Forces the AppFramework to set/clear the APS Retry option (in APS Fram ...", NULL),
  emberCommandEntryTerminator(),
};
void optionBindingTableClearCommand(void);
void optionBindingTablePrintCommand(void);
void optionBindingTableSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionBindingTableSetCommandArguments[] = {
  "one byte index into the binding table",
  "cluster id to send with the discovery message",
  "local endpoint to bind",
  "remote endpoint to bind",
  "8 byte IEEE address provided big endian",
  NULL
};
#endif


static EmberCommandEntry emberCommandOptionBindingTableTable[] = {
  emberCommandEntryActionWithDetails("clear", optionBindingTableClearCommand, "", "Clear the binding table", NULL),
  emberCommandEntryActionWithDetails("print", optionBindingTablePrintCommand, "", "Prints out the binding table to the command line.", NULL),
  emberCommandEntryActionWithDetails("set", optionBindingTableSetCommand, "uvuub", "Set a binding table entry for the arguments specified.", optionBindingTableSetCommandArguments),
  emberCommandEntryTerminator(),
};
void optionDiscoverCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionDiscCommandArguments[] = {
  "the profile id to send with the discovery message",
  "cluster id to send with the discovery message",
  NULL
};
#endif


void optionEndDeviceBindCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionEdbCommandArguments[] = {
  "The local endpoint whose simple descriptor will be used to create the  ...",
  NULL
};
#endif


void optionInstallCodeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
static const char * const optionInstallCodeCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "install code including two-byte, little-endian CRC",
  NULL
};
#endif


void optionLinkCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionLinkCommandArguments[] = {
  "index into the link key table",
  "IEEE address to enter into the link key table",
  "link key to enter into the table",
  NULL
};
#endif


void optionPrintRxCommand(void);
void optionPrintRxCommand(void);
static EmberCommandEntry emberCommandOptionPrintRxMsgsTable[] = {
  emberCommandEntryActionWithDetails("disable", optionPrintRxCommand, "", "Disable the printing of received messages.", NULL),
  emberCommandEntryActionWithDetails("enable", optionPrintRxCommand, "", "Enable the printing of received messages.", NULL),
  emberCommandEntryTerminator(),
};
void optionRegisterCommand(void);
void optionApsSecurityCommand(void);
void optionApsSecurityCommand(void);
static EmberCommandEntry emberCommandOptionSecurityApsTable[] = {
  emberCommandEntryActionWithDetails("off", optionApsSecurityCommand, "", "Turns aps security off", NULL),
  emberCommandEntryActionWithDetails("on", optionApsSecurityCommand, "", "Turns aps security on", NULL),
  emberCommandEntryTerminator(),
};
void optionSecurityAllowTrustCenterRejoinUsingWellKnownKey(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyCommandArguments[] = {
  "Whether or not the Trust Center should allow trust center rejoins for  ...",
  NULL
};
#endif


void optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyTimeoutCommandArguments[] = {
  "The number of seconds that trust center rejoins will be responded to u ...",
  NULL
};
#endif


void optionSecuritySetKeyRequestPolicy(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const optionSecuritySetKeyRequestPolicyCommandArguments[] = {
  "The value to assign to emberTrustCenterLinkKeyRequestPolicy",
  "The value to assign to emberAppLinkKeyRequestPolicy",
  NULL
};
#endif


static EmberCommandEntry emberCommandOptionSecurityTable[] = {
  emberCommandEntrySubMenu("aps", emberCommandOptionSecurityApsTable, ""),
  emberCommandEntryActionWithDetails("set-allow-trust-center-rejoin-using-well-known-key", optionSecurityAllowTrustCenterRejoinUsingWellKnownKey, "u", "Set whether or not a Trust Center application will allow trust center  ...", optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyCommandArguments),
  emberCommandEntryActionWithDetails("set-allow-trust-center-rejoin-using-well-known-key-timeout", optionSecurityAllowTrustCenterRejoinUsingWellKnownKeyTimeout, "v", "Sets the number of seconds to allow trust center rejoins for devices u ...", optionSecuritySetAllowTrustCenterRejoinUsingWellKnownKeyTimeoutCommandArguments),
  emberCommandEntryActionWithDetails("set-key-request-policy", optionSecuritySetKeyRequestPolicy, "uu", "Sets the local policy for handling TC link key requests and applicatio ...", optionSecuritySetKeyRequestPolicyCommandArguments),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandOptionTable[] = {
  emberCommandEntrySubMenu("apsretry", emberCommandOptionApsretryTable, ""),
  emberCommandEntrySubMenu("binding-table", emberCommandOptionBindingTableTable, ""),
  emberCommandEntryActionWithDetails("disc", optionDiscoverCommand, "vv", "Sends a ZDO Match Descriptor Request for the server side of the specif ...", optionDiscCommandArguments),
  emberCommandEntryActionWithDetails("edb", optionEndDeviceBindCommand, "u", "Sends a ZDO End Device Bind Request using the given local endpoint.", optionEdbCommandArguments),
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("install-code", optionInstallCodeCommand, "ubb", "Derives a link key from an install code, sets it in the transient key  ...", optionInstallCodeCommandArguments),
#endif //!defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("link", optionLinkCommand, "ubb", "Sets a link key in the link key tabl ...", optionLinkCommandArguments),
  emberCommandEntrySubMenu("print-rx-msgs", emberCommandOptionPrintRxMsgsTable, ""),
  emberCommandEntryActionWithDetails("register", optionRegisterCommand, "", "Initiates Smart Energy Registration including Key Establishmen ...", NULL),
  emberCommandEntrySubMenu("security", emberCommandOptionSecurityTable, ""),
  emberCommandEntryTerminator(),
};
void emberAfPluginAddressTableAddCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableAddCommandArguments[] = {
  "Entry to be added.",
  NULL
};
#endif


void emberAfPluginAddressTableLookupCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableLookupCommandArguments[] = {
  "Entry to be looked up.",
  NULL
};
#endif


void emberAfPluginAddressTablePrintCommand(void);
void emberAfPluginAddressTableRemoveCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableRemoveCommandArguments[] = {
  "Entry to be removed.",
  NULL
};
#endif


void emberAfPluginAddressTableSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginAddressTableSetCommandArguments[] = {
  "index",
  "eui64",
  "node id",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginAddressTableTable[] = {
  emberCommandEntryActionWithDetails("add", emberAfPluginAddressTableAddCommand, "b", "Add an entry to the address table.", pluginAddressTableAddCommandArguments),
  emberCommandEntryActionWithDetails("lookup", emberAfPluginAddressTableLookupCommand, "b", "Lookup an entry in the address table.", pluginAddressTableLookupCommandArguments),
  emberCommandEntryActionWithDetails("print", emberAfPluginAddressTablePrintCommand, "", "Prints the address table.", NULL),
  emberCommandEntryActionWithDetails("remove", emberAfPluginAddressTableRemoveCommand, "b", "Remove an entry from the address table.", pluginAddressTableRemoveCommandArguments),
  emberCommandEntryActionWithDetails("set", emberAfPluginAddressTableSetCommand, "ubv", "Set an entry in the address table according to the arguments specified", pluginAddressTableSetCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginCounterPrintCounterTypeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginCounterPrintCounterTypeCommandArguments[] = {
  "The counter type       to print.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginCounterTable[] = {
  emberCommandEntryActionWithDetails("print-counter-type", emberAfPluginCounterPrintCounterTypeCommand, "u", "Print value of this particular counter.", pluginCounterPrintCounterTypeCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginCountersClear(void);
void emberAfPluginCountersPrintCommand(void);
void emberAfPluginCountersPrintThresholdsCommand(void);
void emberAfPluginCountersResetThresholds(void);
void emberAfPluginCountersSendRequestCommand(void);
void emberAfPluginCountersSetThresholdCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginCountersSetThresholdCommandArguments[] = {
  "type of counter",
  "Threshold Value",
  NULL
};
#endif


void emberAfPluginCountersSimplePrintCommand(void);
static EmberCommandEntry emberCommandPluginCountersTable[] = {
  emberCommandEntryActionWithDetails("clear", emberAfPluginCountersClear, "", "Clear all counter values.", NULL),
  emberCommandEntryActionWithDetails("print", emberAfPluginCountersPrintCommand, "", "Print all counter values and clear them.", NULL),
  emberCommandEntryActionWithDetails("print-thresholds", emberAfPluginCountersPrintThresholdsCommand, "", "Prints the thresholds of all the counters.", NULL),
  emberCommandEntryActionWithDetails("reset-threshold", emberAfPluginCountersResetThresholds, "", "Resets all thresholds values to 0xFFFF.", NULL),
  emberCommandEntryActionWithDetails("send-request", emberAfPluginCountersSendRequestCommand, "", "Sends a request for ota counters", NULL),
  emberCommandEntryActionWithDetails("set-threshold", emberAfPluginCountersSetThresholdCommand, "uv", "Set a threshold value for a particular type of counter.", pluginCountersSetThresholdCommandArguments),
  emberCommandEntryActionWithDetails("simple-print", emberAfPluginCountersSimplePrintCommand, "", "Print all counter values.", NULL),
  emberCommandEntryTerminator(),
};
void emberAfPluginFindAndBindTargetStartCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginFindAndBindTargetCommandArguments[] = {
  "The endpoint on which to begin the Finding and Binding target process.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginFindAndBindTable[] = {
  emberCommandEntryActionWithDetails("target", emberAfPluginFindAndBindTargetStartCommand, "u", "Makes this node start identifying as a target for binding with an init ...", pluginFindAndBindTargetCommandArguments),
  emberCommandEntryTerminator(),
};
void emAfGroupsServerCliClear(void);
void emAfGroupsServerCliPrint(void);
static EmberCommandEntry emberCommandPluginGroupsServerTable[] = {
  emberCommandEntryActionWithDetails("clear", emAfGroupsServerCliClear, "", "Clear the groups table on every endpoint.", NULL),
  emberCommandEntryActionWithDetails("print", emAfGroupsServerCliPrint, "", "Print information about the contents of the groups table.", NULL),
  emberCommandEntryTerminator(),
};
void emAfPluginIdentifyCliPrint(void);
static EmberCommandEntry emberCommandPluginIdentifyTable[] = {
  emberCommandEntryActionWithDetails("print", emAfPluginIdentifyCliPrint, "", "Print which endpoints are reporting.", NULL),
  emberCommandEntryTerminator(),
};
void emberAfPluginIdleSleepAwakeWhenNotJoinedCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginIdleSleepAwakeWhenNotJoinedCommandArguments[] = {
  "The value indicating whether the device should stay awake when not joi ...",
  NULL
};
#endif


void emberAfPluginIdleSleepStayAwakeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginIdleSleepForceAwakeCommandArguments[] = {
  "The value indicating whether the device should stay awake.",
  NULL
};
#endif


void emberAfPluginIdleSleepStatusCommand(void);
static EmberCommandEntry emberCommandPluginIdleSleepTable[] = {
  emberCommandEntryActionWithDetails("awake-when-not-joined", emberAfPluginIdleSleepAwakeWhenNotJoinedCommand, "u", "Sets whether the device stays awake when not joined to a ZigBee networ ...", pluginIdleSleepAwakeWhenNotJoinedCommandArguments),
  emberCommandEntryActionWithDetails("force-awake", emberAfPluginIdleSleepStayAwakeCommand, "u", "Sets whether the device is forced to stay awake.", pluginIdleSleepForceAwakeCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPluginIdleSleepStatusCommand, "", "Display the status of the sleeping behavior.", NULL),
  emberCommandEntryTerminator(),
};
void emberAfPluginNetworkSteeringChannelAddOrSubtractCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginNetworkSteeringMaskAddCommandArguments[] = {
  "The channel mask to add a channel to.",
  "The channel to add to the mask.",
  NULL
};
#endif


void emberAfPluginNetworkSteeringChannelSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginNetworkSteeringMaskSetCommandArguments[] = {
  "The channel mask to subtract the channel from.",
  "The value to set the channel mask to.",
  NULL
};
#endif


void emberAfPluginNetworkSteeringChannelAddOrSubtractCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginNetworkSteeringMaskSubtractCommandArguments[] = {
  "The channel mask to subtract the channel from.",
  "The channel to subtract the mask from.",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginNetworkSteeringMaskTable[] = {
  emberCommandEntryActionWithDetails("add", emberAfPluginNetworkSteeringChannelAddOrSubtractCommand, "uu", "Adds a channel to either the primary or secondary channel mask of the  ...", pluginNetworkSteeringMaskAddCommandArguments),
  emberCommandEntryActionWithDetails("set", emberAfPluginNetworkSteeringChannelSetCommand, "uw", "Set either the primary or secondary channel mask.", pluginNetworkSteeringMaskSetCommandArguments),
  emberCommandEntryActionWithDetails("subtract", emberAfPluginNetworkSteeringChannelAddOrSubtractCommand, "uu", "Subtracts a channel from either the primary or secondary channel mask  ...", pluginNetworkSteeringMaskSubtractCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginNetworkSteeringSetPreconfiguredKeyCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginNetworkSteeringPreConfiguredKeySetCommandArguments[] = {
  "Set the preconfigured key so that the joining device can enter the net ...",
  NULL
};
#endif


void emberAfPluginNetworkSteeringStartCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginNetworkSteeringStartCommandArguments[] = {
  "A mask of options for indicating specific behavior within the network- ...",
  NULL
};
#endif


void emberAfPluginNetworkSteeringStatusCommand(void);
void emberAfPluginNetworkSteeringStopCommand(void);
static EmberCommandEntry emberCommandPluginNetworkSteeringTable[] = {
  emberCommandEntrySubMenu("mask", emberCommandPluginNetworkSteeringMaskTable, ""),
  emberCommandEntryActionWithDetails("pre-configured-key-set", emberAfPluginNetworkSteeringSetPreconfiguredKeyCommand, "b", "Set the pre-configured key", pluginNetworkSteeringPreConfiguredKeySetCommandArguments),
  emberCommandEntryActionWithDetails("start", emberAfPluginNetworkSteeringStartCommand, "u", "Starts the network steering process.", pluginNetworkSteeringStartCommandArguments),
  emberCommandEntryActionWithDetails("status", emberAfPluginNetworkSteeringStatusCommand, "", "Displays the current status of the network steering process.", NULL),
  emberCommandEntryActionWithDetails("stop", emberAfPluginNetworkSteeringStopCommand, "", "Stops the network steering process.", NULL),
  emberCommandEntryTerminator(),
};
void emAfPluginReportingCliAdd(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginReportingAddCommandArguments[] = {
  "The local endpoint from which the attribute is reported.",
  "The cluster where the attribute is located.",
  "The id of the attribute being reported.",
  "0 for client-side attributes or 1 for server-side attributes.",
  "The minimum reporting interval, measured in seconds.",
  "The maximum reporting interval, measured in seconds.",
  "The minimum change to the attribute that will result in a report being ...",
  NULL
};
#endif


void emAfPluginReportingCliClear(void);
void emAfPluginReportingCliClearLastReportTime(void);
void emAfPluginReportingCliPrint(void);
void emAfPluginReportingCliRemove(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginReportingRemoveCommandArguments[] = {
  "The index of the report to be removed.",
  NULL
};
#endif


void emAfPluginReportingCliTestTiming(void);
static EmberCommandEntry emberCommandPluginReportingTable[] = {
  emberCommandEntryActionWithDetails("add", emAfPluginReportingCliAdd, "uvvuvvw", "Add a new entry to the report table.", pluginReportingAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", emAfPluginReportingCliClear, "", "Clear all entries from the report table.", NULL),
  emberCommandEntryActionWithDetails("clear-last-report-time", emAfPluginReportingCliClearLastReportTime, "", "Clear last report time of attributes.", NULL),
  emberCommandEntryActionWithDetails("print", emAfPluginReportingCliPrint, "", "Print the report table.", NULL),
  emberCommandEntryActionWithDetails("remove", emAfPluginReportingCliRemove, "u", "Remove an entry from the report table.", pluginReportingRemoveCommandArguments),
  emberCommandEntryActionWithDetails("test-timing", emAfPluginReportingCliTestTiming, "", "FOR TESTING PURPOSES - gather timing metrics for reporting table opera ...", NULL),
  emberCommandEntryTerminator(),
};
void emAfPluginScenesServerClear(void);
void emAfPluginScenesServerPrintInfo(void);
static EmberCommandEntry emberCommandPluginScenesTable[] = {
  emberCommandEntryActionWithDetails("clear", emAfPluginScenesServerClear, "", "Clear the scenes table on every endpoint.", NULL),
  emberCommandEntryActionWithDetails("print", emAfPluginScenesServerPrintInfo, "", "Print information about the contents of the scenes table.", NULL),
  emberCommandEntryTerminator(),
};
void emAfPluginSimpleMeteringClientCliGetSampledData(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSimpleMeteringClientGetSampledDataCommandArguments[] = {
  "The network address of the server to which the request will be sent.",
  "The local endpoint from which the request will be sent.",
  "The remote endpoint to which the request will be sent.",
  "The sample id as received in a previous startSamplingResponse",
  "The earliest start time sampling",
  "An 8 bit enumeration that identifies the required type of sampled data",
  "The total number of samples.",
  NULL
};
#endif


void emAfPluginSimpleMeteringClientCliLocalChangeSupply(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSimpleMeteringClientLocalChangeSupplyCommandArguments[] = {
  "The network address of the server to which the request will be sent.",
  "The local endpoint from which the request will be sent.",
  "The remote endpoint to which the request will be sent.",
  "The proposed supply status: either ON(2) or OFF/ARMED(1)",
  NULL
};
#endif


void emAfPluginSimpleMeteringClientCliSchSnapshot(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSimpleMeteringClientSchSnapshotCommandArguments[] = {
  "The network address of the server to which the request will be sent.",
  "The local endpoint from which the request will be sent.",
  "The remote endpoint to which the request will be sent.",
  "The issuerId.",
  "The commandIndex.",
  "The total number of commands",
  "The snapshot schedule Id.",
  "The start time.",
  "The snapshot schedule. 3 bytes",
  "The snapshot Type.",
  "The snapshot schedule cause.",
  NULL
};
#endif


void emAfPluginSimpleMeteringClientCliStartSampling(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginSimpleMeteringClientStartSamplingCommandArguments[] = {
  "The network address of the server to which the request will be sent.",
  "The local endpoint from which the request will be sent.",
  "The remote endpoint to which the request will be sent.",
  "The issuerId.",
  "The time to start sampling",
  "An 8 bit enumeration that identifies the type of data being sampled",
  "An unsigned 16-bit field representing the interval or time in seconds  ...",
  "A 16 bit unsigned integer that represents the number of samples to be  ...",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginSimpleMeteringClientTable[] = {
  emberCommandEntryActionWithDetails("get-sampled-data", emAfPluginSimpleMeteringClientCliGetSampledData, "vuuvwuv", "Send a start sampling command to a metering server.", pluginSimpleMeteringClientGetSampledDataCommandArguments),
  emberCommandEntryActionWithDetails("local-change-supply", emAfPluginSimpleMeteringClientCliLocalChangeSupply, "vuuu", "Send a start sampling command to a metering server.", pluginSimpleMeteringClientLocalChangeSupplyCommandArguments),
  emberCommandEntryActionWithDetails("sch-snapshot", emAfPluginSimpleMeteringClientCliSchSnapshot, "vuuwuuuwwuw", "Schedule a snapshot.", pluginSimpleMeteringClientSchSnapshotCommandArguments),
  emberCommandEntryActionWithDetails("start-sampling", emAfPluginSimpleMeteringClientCliStartSampling, "vuuwwuvv", "Send a start sampling command to a metering server.", pluginSimpleMeteringClientStartSamplingCommandArguments),
  emberCommandEntryTerminator(),
};
void emberAfPluginSetTCLinkKeyUpdateTimerCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const pluginUpdateTcLinkKeyTimerCommandArguments[] = {
  "The amount of time between subsequent trust center link key updates in ...",
  NULL
};
#endif


static EmberCommandEntry emberCommandPluginUpdateTcLinkKeyTable[] = {
  emberCommandEntryActionWithDetails("timer", emberAfPluginSetTCLinkKeyUpdateTimerCommand, "w", "This sets the the amount of time between subsequent trust center link  ...", pluginUpdateTcLinkKeyTimerCommandArguments),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandPluginTable[] = {
  emberCommandEntrySubMenu("address-table", emberCommandPluginAddressTableTable, ""),
  emberCommandEntrySubMenu("counter", emberCommandPluginCounterTable, ""),
  emberCommandEntrySubMenu("counters", emberCommandPluginCountersTable, ""),
  emberCommandEntrySubMenu("find-and-bind", emberCommandPluginFindAndBindTable, ""),
  emberCommandEntrySubMenu("groups-server", emberCommandPluginGroupsServerTable, ""),
  emberCommandEntrySubMenu("identify", emberCommandPluginIdentifyTable, ""),
  emberCommandEntrySubMenu("idle-sleep", emberCommandPluginIdleSleepTable, ""),
  emberCommandEntrySubMenu("network-steering", emberCommandPluginNetworkSteeringTable, ""),
  emberCommandEntrySubMenu("reporting", emberCommandPluginReportingTable, ""),
  emberCommandEntrySubMenu("scenes", emberCommandPluginScenesTable, ""),
  emberCommandEntrySubMenu("simple-metering-client", emberCommandPluginSimpleMeteringClientTable, ""),
  emberCommandEntrySubMenu("update-tc-link-key", emberCommandPluginUpdateTcLinkKeyTable, ""),
  emberCommandEntryTerminator(),
};
void emberAfPrintAttributeTable(void);
void emberAfPrintEntropySource(void);
static EmberCommandEntry emberCommandPrintEntropyTable[] = {
  emberCommandEntryActionWithDetails("source", emberAfPrintEntropySource, "", "Print the the entropy source that is used for true random number gener ...", NULL),
  emberCommandEntryTerminator(),
};
void printTimeCommand(void);
static EmberCommandEntry emberCommandPrintTable[] = {
  emberCommandEntryActionWithDetails("attr", emberAfPrintAttributeTable, "", "Print the attribute table.", NULL),
  emberCommandEntrySubMenu("entropy", emberCommandPrintEntropyTable, ""),
  emberCommandEntryActionWithDetails("time", printTimeCommand, "", "Print out the time information", NULL),
  emberCommandEntryTerminator(),
};
void emAfCliRawCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const rawCommandArguments[] = {
  "two byte cluster id",
  "ZCL message, including ZCL header and payload",
  NULL
};
#endif


void emAfCliReadCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const readCommandArguments[] = {
  "endpoint of the attribute to read",
  "cluster id of the attribute to read",
  "attribute id of the attribute to read",
  "direction mask of the attribute to read (client=0 or server=1)",
  NULL
};
#endif


void resetCommand(void);
void getSetMfgToken(void);
void getSetMfgToken(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD) && !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
static const char * const securityMfgTokenSetCommandArguments[] = {
  "magic number",
  "value",
  NULL
};
#endif


static EmberCommandEntry emberCommandSecurityMfgTokenTable[] = {
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("get", getSetMfgToken, "", "", NULL),
#endif //!defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
#if !defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryActionWithDetails("set", getSetMfgToken, "wv", "", securityMfgTokenSetCommandArguments),
#endif //!defined(EMBER_AF_HAS_SECURITY_PROFILE_NONE)
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandSecurityTable[] = {
  emberCommandEntrySubMenu("mfg-token", emberCommandSecurityMfgTokenTable, ""),
  emberCommandEntryTerminator(),
};
void emAfCliSendCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const sendCommandArguments[] = {
  "short id of the device to send the message to",
  "The endpoint to send the message from",
  "The endpoint to send the message to",
  NULL
};
#endif


void emAfCliSendUsingMulticastBindingCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const sendUsingMulticastBindingCommandArguments[] = {
  "Whether to send via a multicast binding",
  NULL
};
#endif


void emAfCliSendCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const sendMulticastCommandArguments[] = {
  "group id of the multicast group to send the message to",
  "The endpoint to send the message from",
  NULL
};
#endif


void emAfCliTimesyncCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const timesyncCommandArguments[] = {
  "two byte short id of the time server",
  "source endpoint to send time sync from",
  "destination endpoint to expect response on",
  NULL
};
#endif


void emAfCliVersionCommand(void);
void emAfCliWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const writeCommandArguments[] = {
  "endpoint of the attribute to write",
  "cluster id of the attribute to write",
  "attribute id of the attribute to write",
  "direction mask of the attribute to write (client=0 or server=1)",
  "the attribute type as listed in the generated file attribute-type.h",
  "string of bytes you wish to write into the attribute table.",
  NULL
};
#endif


static void zclBasicGlsrCommand(void) {
  zclSimpleServerCommand( ZCL_BASIC_CLUSTER_ID,
                          ZCL_GET_LOCALES_SUPPORTED_RESPONSE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclBasicGlsrCommandArguments[] = {
  "discovery complete",
  "locale supported",
  "",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclBasicTable[] = {
  emberCommandEntryActionWithDetails("glsr", zclBasicGlsrCommand, "ub*", "The locales supported response command is sent in response to a get lo ...", zclBasicGlsrCommandArguments),
  emberCommandEntryTerminator(),
};
void zclGlobalDirectionCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDirectionCommandArguments[] = {
  "The direction for global commands, 0 = client to server, 1 = server to ...",
  NULL
};
#endif


void zclGlobalCommandDiscoveryCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDiscComGenCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};
#endif


void zclGlobalCommandDiscoveryCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDiscComRecCommandArguments[] = {
  "The cluster to find commands on.",
  "The command id to start the command search on.",
  "Max command ids to search for.",
  NULL
};
#endif


void zclGlobalDiscoverCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalDiscoverCommandArguments[] = {
  "The cluster id of the cluster to discover.",
  "The attribute id of the attribute to read during discovery.",
  "Max number of discovery responses.",
  NULL
};
#endif


void zclGlobalExpectReportFromMeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalExpectReportFromMeCommandArguments[] = {
  "The cluster id for the requested report.",
  "The attribute id for the requested report.",
  "Maximum amount of time between reports.",
  NULL
};
#endif


void zclGlobalWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalNwriteCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};
#endif


void zclGlobalReadCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalReadCommandArguments[] = {
  "The cluster id of the cluster to read from.",
  "The attribute id of the attribute to read.",
  NULL
};
#endif


void zclGlobalReportCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalReportCommandArguments[] = {
  "The desired endpoint.",
  "The cluster id.",
  "The attribute id.",
  "The mask.",
  NULL
};
#endif


void zclGlobalReportReadCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalReportReadCommandArguments[] = {
  "The cluster id to read from.",
  "The attribute id to read from.",
  "0 for client-to-server, 1 for server-to-client.",
  NULL
};
#endif


void zclGlobalSendMeAReportCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalSendMeAReportCommandArguments[] = {
  "The cluster id of the requested report.",
  "The attribute id for requested report.",
  "The two byte ZigBee type value for the requested report.",
  "Minimum number of seconds between reports.",
  "Maximum number of seconds between reports.",
  "Amount of change to trigger a report.",
  NULL
};
#endif


void zclGlobalWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalUwriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};
#endif


void zclGlobalWriteCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclGlobalWriteCommandArguments[] = {
  "The cluster id of the cluster to write to.",
  "The attribute id of the attribute to write.",
  "The type of the attribute to write.",
  "The data to be written.",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclGlobalTable[] = {
  emberCommandEntryActionWithDetails("direction", zclGlobalDirectionCommand, "u", "Sets the direction for global commands, either client to server or ser ...", zclGlobalDirectionCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-gen", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Generated command with associated values.", zclGlobalDiscComGenCommandArguments),
  emberCommandEntryActionWithDetails("disc-com-rec", zclGlobalCommandDiscoveryCommand, "vuu", "Create a Discover Commands Received command with associated values.", zclGlobalDiscComRecCommandArguments),
  emberCommandEntryActionWithDetails("discover", zclGlobalDiscoverCommand, "vvu", "Creates discovery message for devices with the associated cluster and  ...", zclGlobalDiscoverCommandArguments),
  emberCommandEntryActionWithDetails("expect-report-from-me", zclGlobalExpectReportFromMeCommand, "vvv", "Create a expect-report-from-me message with associated values.", zclGlobalExpectReportFromMeCommandArguments),
  emberCommandEntryActionWithDetails("nwrite", zclGlobalWriteCommand, "vvub", "Creates a global write command message to write to the cluster and att ...", zclGlobalNwriteCommandArguments),
  emberCommandEntryActionWithDetails("read", zclGlobalReadCommand, "vv", "Creates a global read command message to read from the cluster and att ...", zclGlobalReadCommandArguments),
  emberCommandEntryActionWithDetails("report", zclGlobalReportCommand, "uvvu", "", zclGlobalReportCommandArguments),
  emberCommandEntryActionWithDetails("report-read", zclGlobalReportReadCommand, "vvu", "Creates a global read reporting command for the associated cluster, at ...", zclGlobalReportReadCommandArguments),
  emberCommandEntryActionWithDetails("send-me-a-report", zclGlobalSendMeAReportCommand, "vvuvvb", "Creates a global send me a report command for the associated values.", zclGlobalSendMeAReportCommandArguments),
  emberCommandEntryActionWithDetails("uwrite", zclGlobalWriteCommand, "vvub", "Creates a global write undivided command message to write to the clust ...", zclGlobalUwriteCommandArguments),
  emberCommandEntryActionWithDetails("write", zclGlobalWriteCommand, "vvwb", "Creates a global write command message to write to the cluster and att ...", zclGlobalWriteCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclIdentifyEzModeCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_E_Z_MODE_INVOKE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclIdentifyEzModeCommandArguments[] = {
  "action",
  NULL
};
#endif


static void zclIdentifyIdCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclIdentifyIdCommandArguments[] = {
  "identify time",
  NULL
};
#endif


void zclIdentifyOnOffCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclIdentifyOffCommandArguments[] = {
  "The endpoint on which to stop identifying",
  NULL
};
#endif


void zclIdentifyOnOffCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclIdentifyOnCommandArguments[] = {
  "The endpoint on the device which should begin identifying",
  "The number of seconds to spend identifying",
  NULL
};
#endif


static void zclIdentifyQueryCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_IDENTIFY_QUERY_COMMAND_ID);
}

static void zclIdentifyTriggerCommand(void) {
  zclSimpleClientCommand( ZCL_IDENTIFY_CLUSTER_ID,
                          ZCL_TRIGGER_EFFECT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclIdentifyTriggerCommandArguments[] = {
  "effect id",
  "effect variant",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclIdentifyTable[] = {
  emberCommandEntryActionWithDetails("ez-mode", zclIdentifyEzModeCommand, "u", "Invoke EZMode on an Identify Server", zclIdentifyEzModeCommandArguments),
  emberCommandEntryActionWithDetails("id", zclIdentifyIdCommand, "v", "Command description for Identify", zclIdentifyIdCommandArguments),
  emberCommandEntryActionWithDetails("off", zclIdentifyOnOffCommand, "u", "Writes the IdentifyTime attribute", zclIdentifyOffCommandArguments),
  emberCommandEntryActionWithDetails("on", zclIdentifyOnOffCommand, "uv", "Writes the IdentifyTime attribute", zclIdentifyOnCommandArguments),
  emberCommandEntryActionWithDetails("query", zclIdentifyQueryCommand, "", "Command description for IdentifyQuery", NULL),
  emberCommandEntryActionWithDetails("trigger", zclIdentifyTriggerCommand, "uu", "Command description for TriggerEffect", zclIdentifyTriggerCommandArguments),
  emberCommandEntryTerminator(),
};
static void zclMeteringChgSupplyCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_CHANGE_SUPPLY_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringChgSupplyCommandArguments[] = {
  "provider id",
  "issuer event id",
  "request date time",
  "implementation date time",
  "proposed supply status",
  "supply control bits",
  NULL
};
#endif


static void zclMeteringGetProfileCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_PROFILE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringGetProfileCommandArguments[] = {
  "interval channel",
  "end time",
  "number of periods",
  NULL
};
#endif


static void zclMeteringGetSampledDataCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_SAMPLED_DATA_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringGetSampledDataCommandArguments[] = {
  "sample id",
  "earliest sample time",
  "sample type",
  "number of samples",
  NULL
};
#endif


static void zclMeteringGetSnapshotCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_GET_SNAPSHOT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringGetSnapshotCommandArguments[] = {
  "earliest start time",
  "latest end time",
  "snapshot offset",
  "snapshot cause",
  NULL
};
#endif


static void zclMeteringLocalChgSupplyCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_LOCAL_CHANGE_SUPPLY_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringLocalChgSupplyCommandArguments[] = {
  "proposed supply status",
  NULL
};
#endif


static void zclMeteringMirrorRemovedCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_MIRROR_REMOVED_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringMirrorRemovedCommandArguments[] = {
  "endpoint id",
  NULL
};
#endif


static void zclMeteringReqFastPollModeCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_REQUEST_FAST_POLL_MODE_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringReqFastPollModeCommandArguments[] = {
  "fast poll update period",
  "duration",
  NULL
};
#endif


static void zclMeteringRstLoadLimitCtrCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_RESET_LOAD_LIMIT_COUNTER_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringRstLoadLimitCtrCommandArguments[] = {
  "provider id",
  "issuer event id",
  NULL
};
#endif


static void zclMeteringSchSnapshotCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SCHEDULE_SNAPSHOT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringSchSnapshotCommandArguments[] = {
  "issuer event id",
  "command index",
  "command count",
  "snapshot schedule payload",
  "",
  NULL
};
#endif


static void zclMeteringSetSupplyStatusCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SET_SUPPLY_STATUS_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringSetSupplyStatusCommandArguments[] = {
  "issuer event id",
  "supply tamper state",
  "supply depletion state",
  "supply uncontrolled flow state",
  "load limit supply state",
  NULL
};
#endif


static void zclMeteringSetUncntrlFlowThresholdCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_SET_UNCONTROLLED_FLOW_THRESHOLD_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringSetUncntrlFlowThresholdCommandArguments[] = {
  "provider id",
  "issuer event id",
  "uncontrolled flow threshold",
  "unit of measure",
  "multiplier",
  "divisor",
  "stabilisation period",
  "measurement period",
  NULL
};
#endif


static void zclMeteringStartSamplingCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_START_SAMPLING_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringStartSamplingCommandArguments[] = {
  "issuer event id",
  "start sampling time",
  "sample type",
  "sample request interval",
  "max number of samples",
  NULL
};
#endif


static void zclMeteringTakeSnapshotCommand(void) {
  zclSimpleClientCommand( ZCL_SIMPLE_METERING_CLUSTER_ID,
                          ZCL_TAKE_SNAPSHOT_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMeteringTakeSnapshotCommandArguments[] = {
  "snapshot cause",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclMeteringTable[] = {
  emberCommandEntryActionWithDetails("chg-supply", zclMeteringChgSupplyCommand, "wwwwuu", "This command is sent from the Head-end or ESI to the Metering Device t ...", zclMeteringChgSupplyCommandArguments),
  emberCommandEntryActionWithDetails("get-profile", zclMeteringGetProfileCommand, "uwu", "The GetProfile command is generated when a client device wishes to ret ...", zclMeteringGetProfileCommandArguments),
  emberCommandEntryActionWithDetails("get-sampled-data", zclMeteringGetSampledDataCommand, "vwuv", "This command is used to request sampled data from the serve ...", zclMeteringGetSampledDataCommandArguments),
  emberCommandEntryActionWithDetails("get-snapshot", zclMeteringGetSnapshotCommand, "wwuw", "This command is used to request snapshot data from the cluster server.", zclMeteringGetSnapshotCommandArguments),
  emberCommandEntryActionWithDetails("local-chg-supply", zclMeteringLocalChgSupplyCommand, "u", "This command is a simplified version of the ChangeSupply command, inte ...", zclMeteringLocalChgSupplyCommandArguments),
  emberCommandEntryActionWithDetails("mirror-removed", zclMeteringMirrorRemovedCommand, "v", "The Mirror Removed Command allows the ESI to inform a sleepy Metering  ...", zclMeteringMirrorRemovedCommandArguments),
  emberCommandEntryActionWithDetails("req-fast-poll-mode", zclMeteringReqFastPollModeCommand, "uu", "The Request Fast Poll Mode command is generated when the metering clie ...", zclMeteringReqFastPollModeCommandArguments),
  emberCommandEntryActionWithDetails("rst-load-limit-ctr", zclMeteringRstLoadLimitCtrCommand, "ww", "The ResetLoadLimitCounter command shall cause the LoadLimitCounter att ...", zclMeteringRstLoadLimitCtrCommandArguments),
  emberCommandEntryActionWithDetails("sch-snapshot", zclMeteringSchSnapshotCommand, "wuub*", "This command is used to set up a schedule of when the device shall cre ...", zclMeteringSchSnapshotCommandArguments),
  emberCommandEntryActionWithDetails("set-supply-status", zclMeteringSetSupplyStatusCommand, "wuuuu", "This command is used to specify the required status of the supply foll ...", zclMeteringSetSupplyStatusCommandArguments),
  emberCommandEntryActionWithDetails("set-uncntrl-flow-threshold", zclMeteringSetUncntrlFlowThresholdCommand, "wwvuvvuv", "This command is used to update the 'Uncontrolled Flow Rate' configurat ...", zclMeteringSetUncntrlFlowThresholdCommandArguments),
  emberCommandEntryActionWithDetails("start-sampling", zclMeteringStartSamplingCommand, "wwuvv", "The sampling mechanism allows a set of samples of the specified type o ...", zclMeteringStartSamplingCommandArguments),
  emberCommandEntryActionWithDetails("take-snapshot", zclMeteringTakeSnapshotCommand, "w", "This command is used to instruct the cluster server to take a single s ...", zclMeteringTakeSnapshotCommandArguments),
  emberCommandEntryTerminator(),
};
void zclMfgCodeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclMfgCodeCommandArguments[] = {
  "Manufacturer Specific Id",
  NULL
};
#endif


static void zclPowerProfileEnergyPhasesScheduleCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_ENERGY_PHASES_SCHEDULE_NOTIFICATION_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPowerProfileEnergyPhasesScheduleCommandArguments[] = {
  "power profile id",
  "num of scheduled phases",
  "scheduled phases",
  "",
  NULL
};
#endif


static void zclPowerProfileEnergyPhasesScheduleStatesCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_ENERGY_PHASES_SCHEDULE_STATE_REQUEST_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPowerProfileEnergyPhasesScheduleStatesCommandArguments[] = {
  "power profile id",
  NULL
};
#endif


static void zclPowerProfileProfileCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_REQUEST_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPowerProfileProfileCommandArguments[] = {
  "power profile id",
  NULL
};
#endif


static void zclPowerProfileScheduleConstraintsCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_SCHEDULE_CONSTRAINTS_REQUEST_COMMAND_ID);
}

#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclPowerProfileScheduleConstraintsCommandArguments[] = {
  "power profile id",
  NULL
};
#endif


static void zclPowerProfileStateCommand(void) {
  zclSimpleClientCommand( ZCL_POWER_PROFILE_CLUSTER_ID,
                          ZCL_POWER_PROFILE_STATE_REQUEST_COMMAND_ID);
}

static EmberCommandEntry emberCommandZclPowerProfileTable[] = {
  emberCommandEntryActionWithDetails("energy-phases-schedule", zclPowerProfileEnergyPhasesScheduleCommand, "uub*", "The EnergyPhasesScheduleNotification Command is generated by a device  ...", zclPowerProfileEnergyPhasesScheduleCommandArguments),
  emberCommandEntryActionWithDetails("energy-phases-schedule-states", zclPowerProfileEnergyPhasesScheduleStatesCommand, "u", "The EnergyPhasesScheduleStateRequest  Command is generated by a device ...", zclPowerProfileEnergyPhasesScheduleStatesCommandArguments),
  emberCommandEntryActionWithDetails("profile", zclPowerProfileProfileCommand, "u", "The PowerProfileRequest Command is generated by a device supporting th ...", zclPowerProfileProfileCommandArguments),
  emberCommandEntryActionWithDetails("schedule-constraints", zclPowerProfileScheduleConstraintsCommand, "u", "The PowerProfileScheduleConstraintsRequest Command is generated by a d ...", zclPowerProfileScheduleConstraintsCommandArguments),
  emberCommandEntryActionWithDetails("state", zclPowerProfileStateCommand, "", "The PowerProfileStateRequest Command is generated in order to retrieve ...", NULL),
  emberCommandEntryTerminator(),
};
void zclTestResponseOffCommand(void);
void zclTestResponseOnCommand(void);
static EmberCommandEntry emberCommandZclTestResponseTable[] = {
  emberCommandEntryActionWithDetails("off", zclTestResponseOffCommand, "", "Sets a flag so that the application framework WILL NOT respond to the  ...", NULL),
  emberCommandEntryActionWithDetails("on", zclTestResponseOnCommand, "", "Sets a flag so that the application framework WILL respond to the next ...", NULL),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandZclTestTable[] = {
  emberCommandEntrySubMenu("response", emberCommandZclTestResponseTable, ""),
  emberCommandEntryTerminator(),
};
void zclTimeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclTimeCommandArguments[] = {
  "ZigBee UTC time, number of seconds since the year 2000",
  NULL
};
#endif


void zclUseNextSequenceCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclUseNextSequenceCommandArguments[] = {
  "bool value indicating whether raw command will use the incremented seq ...",
  NULL
};
#endif


void zclXDefaultRespCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zclXDefaultRespCommandArguments[] = {
  "bool value indicating whether the disable default response bit is set( ...",
  NULL
};
#endif


static EmberCommandEntry emberCommandZclTable[] = {
  emberCommandEntrySubMenu("basic", emberCommandZclBasicTable, ""),
  emberCommandEntrySubMenu("global", emberCommandZclGlobalTable, ""),
  emberCommandEntrySubMenu("identify", emberCommandZclIdentifyTable, ""),
  emberCommandEntrySubMenu("metering", emberCommandZclMeteringTable, ""),
  emberCommandEntryActionWithDetails("mfg-code", zclMfgCodeCommand, "v", "Sets the two byte manufacturer specific identifier to use for the next ...", zclMfgCodeCommandArguments),
  emberCommandEntrySubMenu("power-profile", emberCommandZclPowerProfileTable, ""),
  emberCommandEntrySubMenu("test", emberCommandZclTestTable, ""),
  emberCommandEntryActionWithDetails("time", zclTimeCommand, "w", "Cli command to call emberAfSetTime function documented in af.h", zclTimeCommandArguments),
  emberCommandEntryActionWithDetails("use-next-sequence", zclUseNextSequenceCommand, "u", "Sets the flag to use the incremented sequence number from the framewor ...", zclUseNextSequenceCommandArguments),
  emberCommandEntryActionWithDetails("x-default-resp", zclXDefaultRespCommand, "u", "Sets the Disable Default Response Frame Control bit to use for the nex ...", zclXDefaultRespCommandArguments),
  emberCommandEntryTerminator(),
};
void zdoActiveEpCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoActiveCommandArguments[] = {
  "Two byte short id, destination for the active endpoint request",
  NULL
};
#endif


void zdoBindCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoBindCommandArguments[] = {
  "Two byte destination node id",
  "Remote device's source endpoint to bind",
  "Remote endpoint to bind",
  "Cluster on which to bind",
  "Remote node EUI64",
  "Binding's dest EUI64.  Usually the local node's EUI64",
  NULL
};
#endif


void zdoIeeeAddressRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoIeeeCommandArguments[] = {
  "Short address of the device for which a long address is requested",
  NULL
};
#endif


void zdoAddClusterCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoInClListAddCommandArguments[] = {
  "Server cluster id",
  NULL
};
#endif


void zdoClearClusterCommand(void);
static EmberCommandEntry emberCommandZdoInClListTable[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known server (in) clusters on this device.", zdoInClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of server (in) clusters.", NULL),
  emberCommandEntryTerminator(),
};
void zdoLeaveRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoLeaveCommandArguments[] = {
  "Target node ID",
  "Remove children",
  "Rejoin after leave",
  NULL
};
#endif


void zdoMatchCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoMatchCommandArguments[] = {
  "Two byte node id indicating wher",
  "Two byte profile id for the match descriptor request",
  NULL
};
#endif


void zdoMgmtBindCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoMgmtBindCommandArguments[] = {
  "Target node ID",
  "Starting index into table query",
  NULL
};
#endif


void zdoMgmtLqiCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoMgmtLqiCommandArguments[] = {
  "Target node ID",
  "Starting index into table query",
  NULL
};
#endif


void zdoNodeCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNodeCommandArguments[] = {
  "Two byte address for the target device.",
  NULL
};
#endif


void zdoNwkAddressRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkCommandArguments[] = {
  "IEEE address for which a short address is being requested",
  NULL
};
#endif


void zdoNetworkUpdateChannelCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdChanCommandArguments[] = {
  "One byte channel to change to.",
  NULL
};
#endif


void zdoNetworkUpdateChannelCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdChanPgCommandArguments[] = {
  "One byte channel to change to.",
  "One byte page to change to.",
  NULL
};
#endif


void zdoNetworkUpdateScanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdScanCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  NULL
};
#endif


void zdoNetworkUpdateScanCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdScanChanMaskCommandArguments[] = {
  "Two byte short id of the target device",
  "One byte scan duration. Must be in range 0 - 5",
  "Number of scans to perform. Must be in range 1 - 8",
  "Four byte channel mask",
  NULL
};
#endif


void zdoNetworkUpdateSetCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoNwkUpdSetCommandArguments[] = {
  "Two byte network manager id",
  "Four byte channel mask",
  NULL
};
#endif


static EmberCommandEntry emberCommandZdoNwkUpdTable[] = {
  emberCommandEntryActionWithDetails("chan", zdoNetworkUpdateChannelCommand, "u", "Sends an update channel request.", zdoNwkUpdChanCommandArguments),
  emberCommandEntryActionWithDetails("chanPg", zdoNetworkUpdateChannelCommand, "uu", "Sends an update channel page reques ...", zdoNwkUpdChanPgCommandArguments),
  emberCommandEntryActionWithDetails("scan", zdoNetworkUpdateScanCommand, "vuv", "Performs an energy scan.", zdoNwkUpdScanCommandArguments),
  emberCommandEntryActionWithDetails("scan-chan-mask", zdoNetworkUpdateScanCommand, "vuvw", "Performs an energy scan on given channel mas ...", zdoNwkUpdScanChanMaskCommandArguments),
  emberCommandEntryActionWithDetails("set", zdoNetworkUpdateSetCommand, "vw", "Broadcasts the ID of the new network manager and active channels.", zdoNwkUpdSetCommandArguments),
  emberCommandEntryTerminator(),
};
void zdoAddClusterCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoOutClListAddCommandArguments[] = {
  "Client cluster ids",
  NULL
};
#endif


void zdoClearClusterCommand(void);
static EmberCommandEntry emberCommandZdoOutClListTable[] = {
  emberCommandEntryActionWithDetails("add", zdoAddClusterCommand, "v", "Add clusters to the known client (out) clusters on this device.", zdoOutClListAddCommandArguments),
  emberCommandEntryActionWithDetails("clear", zdoClearClusterCommand, "", "Clear the ZDO list of client (out) clusters.", NULL),
  emberCommandEntryTerminator(),
};
void zdoPowerDescriptorRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoPowerCommandArguments[] = {
  "Target node ID",
  NULL
};
#endif


void zdoRouteRequestCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoRouteCommandArguments[] = {
  "Target node ID",
  "The index of the remote node's routing table to request.",
  NULL
};
#endif


void zdoSimpleCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoSimpleCommandArguments[] = {
  "Short address of the device where the simple descriptor request should ...",
  "The endpoint on the target device where the simple descriptor request  ...",
  NULL
};
#endif


void zdoUnbindGroupCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoUnbindGroupCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The group address in the binding",
  NULL
};
#endif


void zdoUnbindUnicastCommand(void);
#if defined(EMBER_COMMAND_INTEPRETER_HAS_DESCRIPTION_FIELD)
static const char * const zdoUnbindUnicastCommandArguments[] = {
  "Target node ID",
  "The source EUI64 of the binding (the remote device's EUI64)",
  "The source endpoint of the binding.",
  "The cluster ID to unbind.",
  "The destination EUI64 in the binding (usually the local node's EUI64",
  "The destination endpoint of the binding",
  NULL
};
#endif


static EmberCommandEntry emberCommandZdoUnbindTable[] = {
  emberCommandEntryActionWithDetails("group", zdoUnbindGroupCommand, "vbuvv", "Sends an unbind request for a multicast binding to the target device.", zdoUnbindGroupCommandArguments),
  emberCommandEntryActionWithDetails("unicast", zdoUnbindUnicastCommand, "vbuvbu", "Sends an unbind request for a unicast binding to the target device.", zdoUnbindUnicastCommandArguments),
  emberCommandEntryTerminator(),
};
static EmberCommandEntry emberCommandZdoTable[] = {
  emberCommandEntryActionWithDetails("active", zdoActiveEpCommand, "v", "Send an active endpoint request to the device with the given short id.", zdoActiveCommandArguments),
  emberCommandEntryActionWithDetails("bind", zdoBindCommand, "vuuvbb", "Send a ZDO Bind command to a device specified in the command arguments ...", zdoBindCommandArguments),
  emberCommandEntryActionWithDetails("ieee", zdoIeeeAddressRequestCommand, "v", "Request an ieee address based on a given node id.", zdoIeeeCommandArguments),
  emberCommandEntrySubMenu("in-cl-list", emberCommandZdoInClListTable, ""),
  emberCommandEntryActionWithDetails("leave", zdoLeaveRequestCommand, "vuu", "Send a ZDO Management Leave command to the target device.", zdoLeaveCommandArguments),
  emberCommandEntryActionWithDetails("match", zdoMatchCommand, "vv", "Sends a matchDescriptorsRequest to the given destination with the give ...", zdoMatchCommandArguments),
  emberCommandEntryActionWithDetails("mgmt-bind", zdoMgmtBindCommand, "vu", "Send a ZDO MGMT-Bind (Binding Table) Request to the target device.", zdoMgmtBindCommandArguments),
  emberCommandEntryActionWithDetails("mgmt-lqi", zdoMgmtLqiCommand, "vu", "Send a ZDO MGMT-LQI (LQI Table) Request to the target device.", zdoMgmtLqiCommandArguments),
  emberCommandEntryActionWithDetails("node", zdoNodeCommand, "v", "Sends a node descriptor request to a given target device", zdoNodeCommandArguments),
  emberCommandEntryActionWithDetails("nwk", zdoNwkAddressRequestCommand, "b", "Sends a network address request for the given IEEE address.", zdoNwkCommandArguments),
  emberCommandEntrySubMenu("nwk-upd", emberCommandZdoNwkUpdTable, ""),
  emberCommandEntrySubMenu("out-cl-list", emberCommandZdoOutClListTable, ""),
  emberCommandEntryActionWithDetails("power", zdoPowerDescriptorRequestCommand, "v", "Send a ZDO Power Descriptor Request to the target device.", zdoPowerCommandArguments),
  emberCommandEntryActionWithDetails("route", zdoRouteRequestCommand, "vu", "Send a ZDO route request command to the target.", zdoRouteCommandArguments),
  emberCommandEntryActionWithDetails("simple", zdoSimpleCommand, "vu", "Sends out a simple descriptor request for the short address and endpoi ...", zdoSimpleCommandArguments),
  emberCommandEntrySubMenu("unbind", emberCommandZdoUnbindTable, ""),
  emberCommandEntryTerminator(),
};
EmberCommandEntry emberCommandTable[] = {
  emberCommandEntryActionWithDetails("bsend", emAfCliBsendCommand, "u", "Send using a binding based on the clusterId in the globalApsFrame and  ...", bsendCommandArguments),
  emberCommandEntrySubMenu("changekey", emberCommandChangekeyTable, ""),
  emberCommandEntrySubMenu("debugprint", emberCommandDebugprintTable, ""),
  emberCommandEntryActionWithDetails("echo", echoCommand, "u", "Turns echo on the command line on or off depending on the argument", echoCommandArguments),
  emberCommandEntrySubMenu("endpoint", emberCommandEndpointTable, ""),
  emberCommandEntryActionWithDetails("events", printEvents, "", "Print the list of timer events.", NULL),
  emberCommandEntryActionWithDetails("help", helpCommand, "", "Prints out the cli command options for the device", NULL),
  emberCommandEntryActionWithDetails("info", emAfCliInfoCommand, "", "Gives information about the local node", NULL),
  emberCommandEntrySubMenu("interpan", emberCommandInterpanTable, ""),
  emberCommandEntrySubMenu("keys", emberCommandKeysTable, ""),
  emberCommandEntryActionWithDetails("libs", printAllLibraryStatus, "", "Lists which optional libraries of the stack are implemented on this de ...", NULL),
  emberCommandEntrySubMenu("network", emberCommandNetworkTable, ""),
  emberCommandEntrySubMenu("option", emberCommandOptionTable, ""),
  emberCommandEntrySubMenu("plugin", emberCommandPluginTable, ""),
  emberCommandEntrySubMenu("print", emberCommandPrintTable, ""),
  emberCommandEntryActionWithDetails("raw", emAfCliRawCommand, "vb", "Creates a message by specifying the raw byte ...", rawCommandArguments),
  emberCommandEntryActionWithDetails("read", emAfCliReadCommand, "uvvu", "Read an attribute from the local attribute tabl ...", readCommandArguments),
  emberCommandEntryActionWithDetails("reset", resetCommand, "", "resets the device", NULL),
  emberCommandEntrySubMenu("security", emberCommandSecurityTable, ""),
  emberCommandEntryActionWithDetails("send", emAfCliSendCommand, "vuu", "Send a pre-buffered message from a given endpoint to an endpoint on a  ...", sendCommandArguments),
  emberCommandEntryActionWithDetails("send-using-multicast-binding", emAfCliSendUsingMulticastBindingCommand, "u", "When sending using a binding, specify whether a multicast binding shou ...", sendUsingMulticastBindingCommandArguments),
  emberCommandEntryActionWithDetails("send_multicast", emAfCliSendCommand, "vu", "Send a pre-buffered multicast message to a given group id from a given ...", sendMulticastCommandArguments),
  emberCommandEntryActionWithDetails("timesync", emAfCliTimesyncCommand, "vuu", "This sends a read attr for the time of the device specifie ...", timesyncCommandArguments),
  emberCommandEntryActionWithDetails("version", emAfCliVersionCommand, "", "Shows the version of the software", NULL),
  emberCommandEntryActionWithDetails("write", emAfCliWriteCommand, "uvvuub", "Write an attribute value into the local attribute table", writeCommandArguments),
  emberCommandEntrySubMenu("zcl", emberCommandZclTable, ""),
  emberCommandEntrySubMenu("zdo", emberCommandZdoTable, ""),
#ifdef EMBER_AF_ENABLE_CUSTOM_COMMANDS
  CUSTOM_COMMANDS
#endif // EMBER_AF_ENABLE_CUSTOM_COMMANDS
  emberCommandEntryTerminator(),
};
